/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.example.demo.model;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.example.demo.model.UserInfo;
import com.example.demo.model.UserInfoResponse;
import java.util.LinkedList;
import java.util.List;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class UserInfoResponse_SSTest extends UserInfoResponse_SSTest_scaffolding {
// allCoveredLines:[7, 9, 10, 11, 12]

  @Test(timeout = 9000)
  public void test_equals_0()  throws Throwable  {
      //caseID:c5e085e5fd83a31b3a71efc126781359
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_Object: userInfoResponse0
      //Assert: assertTrue(method_result);
      
      UserInfoResponse userInfoResponse0 = new UserInfoResponse();
      
      //Call method: equals
      boolean boolean0 = userInfoResponse0.equals(userInfoResponse0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_1()  throws Throwable  {
      //caseID:52b0cf2758b90e56d767a9b59d9f8505
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_Object: 1
      //Assert: assertFalse(method_result);
      
      UserInfoResponse userInfoResponse0 = new UserInfoResponse();
      Integer integer0 = new Integer(1);
      
      //Call method: equals
      boolean boolean0 = userInfoResponse0.equals(integer0);
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_2()  throws Throwable  {
      //caseID:637c9c7c8b2465001404ad576c8d0f6d
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 7, 9, 10, 11, 12]
      //Input_0_Object: userInfoResponse0
      //Assert: assertTrue(method_result);
      
      UserInfoResponse userInfoResponse0 = new UserInfoResponse();
      UserInfoResponse userInfoResponse1 = new UserInfoResponse();
      
      //Call method: equals
      boolean boolean0 = userInfoResponse1.equals(userInfoResponse0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_3()  throws Throwable  {
      //caseID:35869109bff11b43d0fc93fe6be51804
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 7, 9, 10, 11, 12]
      //Input_0_Object: userInfoResponse1
      //Assert: assertTrue(method_result);
      
      UserInfoResponse userInfoResponse0 = new UserInfoResponse();
      UserInfoResponse userInfoResponse1 = new UserInfoResponse();
      
      //Call method: equals
      boolean boolean0 = userInfoResponse0.equals(userInfoResponse1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_hashCode_4()  throws Throwable  {
      //caseID:e644cc6e07b21d3672c45f44bb15510b
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 7, 9, 10, 11, 12]
      
      UserInfoResponse userInfoResponse0 = new UserInfoResponse();
      
      //Call method: hashCode
      userInfoResponse0.hashCode();
  }

  @Test(timeout = 9000)
  public void test_setErrorInfo_5()  throws Throwable  {
      //caseID:e39ef9f529ae4956ecb6cf142840990a
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_String: UserInfoResponse(rowCount=
      
      UserInfoResponse userInfoResponse0 = new UserInfoResponse();
      
      //Call method: setErrorInfo
      userInfoResponse0.setErrorInfo("UserInfoResponse(rowCount=");
      
      //Test Result Assert
      assertNull(userInfoResponse0.getRowCount());
  }

  @Test(timeout = 9000)
  public void test_setErrorNo_6()  throws Throwable  {
      //caseID:f5d06b374f34e81e7fe1967adf779f82
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_Integer: (-1)
      
      UserInfoResponse userInfoResponse0 = new UserInfoResponse();
      Integer integer0 = new Integer((-1));
      
      //Call method: setErrorNo
      userInfoResponse0.setErrorNo(integer0);
      
      //Test Result Assert
      assertEquals((-1), (int)userInfoResponse0.getErrorNo());
  }

  @Test(timeout = 9000)
  public void test_setRowCount_7()  throws Throwable  {
      //caseID:51a18e6bfa92c8b8fde82fad602463d9
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_Integer: 58
      
      UserInfoResponse userInfoResponse0 = new UserInfoResponse();
      Integer integer0 = new Integer(58);
      
      //Call method: setRowCount
      userInfoResponse0.setRowCount(integer0);
      
      //Test Result Assert
      assertNull(userInfoResponse0.getErrorInfo());
  }

  @Test(timeout = 9000)
  public void test_setRows_8()  throws Throwable  {
      //caseID:1a62ea65f2328275068b4cef7e69f48b
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_List<UserInfo>: linkedList0
      
      UserInfoResponse userInfoResponse0 = new UserInfoResponse();
      LinkedList<UserInfo> linkedList0 = new LinkedList<UserInfo>();
      
      //Call method: setRows
      userInfoResponse0.setRows(linkedList0);
      
      //Test Result Assert
      assertNull(userInfoResponse0.getErrorInfo());
  }

  @Test(timeout = 9000)
  public void test_toString_9()  throws Throwable  {
      //caseID:2bb262d6c1ca36d014100497eceb0b7c
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 7, 9, 10, 11, 12]
      //Assert: assertEquals("UserInfoResponse(rowCount=null, rows=null, errorNo=null, errorInfo=null)", method_result);
      
      UserInfoResponse userInfoResponse0 = new UserInfoResponse();
      
      //Call method: toString
      String string0 = userInfoResponse0.toString();
      
      //Test Result Assert
      assertEquals("UserInfoResponse(rowCount=null, rows=null, errorNo=null, errorInfo=null)", string0);
  }
}
